### ISSUE TITLE
Abort

### ISSUE THREAD

**Issue by kalxed** [WPI-HPRC/payload-2024#11]
# Abort
For this issue, follow this general process:

1. Move this task into "In-Progress" once you have begun work on it
2. Clone the payload-2024 repository locally to your computer, and make a second copy if you would like to easily compare branches.
3. Checkout the "TestLaunch1" branch
4. Create a new branch with the naming scheme "<State Name (with number if applicable)>-LIFT", ex. 00-PreLaunch-LIFT
5. Make sure to check out this branch, immediately rename your state to include a number if applicable, this will mirror how the states are named in the "IREC-Dev" branch which you will be comparing with afterwards
6. If you don't already have a second clone of the repository, clone it a second time and checkout the "IREC-Dev" branch
7. Examine the code between the TestLaunch1 branch and the IREC-Dev branch, if there are differences in functionality either note these down to bring to the meeting or change the code *while checked out in your branch* and commit your changes to the branch and push to the remote.
8. Your goal is to ensure that the code within your assigned state is mostly similar to the code that existed at the end of the last year. Ensure your code **builds** before you push it to remote, if it doesn't note that in your commit message

If you have trouble with any of these steps reach out through slack for support.

**Comment by rohan908** [comment]
The abort code has some interesting comments that I don't know if they imply that extra functionality needs to be programmed or the delay is necessary. The code is within the loop of the state:

// shut down all systems, log slowly, retract camera 

    // busy wait
   delay(500)

The previous IREC code from launch day doesn't have anything within its loop. Some guidance would be helpful, thanks! @kalxed

**Comment by kalxed** [comment]
Thankfully, Colette got back to us as well, but I think for now unless you would like to reverse the camera servo extending code, which we haven't yet tested 😢 I would just leave this state be and we can return to it later if you are interested in adding functionality or we come up with a good reason to add it. Like Colette said as well, I don't think we have any transition to Abort in payload states either. So as well it doesn't make sense to work too much on it until it is meant to do something somewhere.
